---
{{- if and .Values.broker.enabled (not .Values.authentication.disable) (or
  (and .Values.authentication.propertiesRealm.enabled
  .Values.authentication.propertiesRealm.credentialsSecretName)
  .Values.authentication.ldapRealm.enabled) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.broker.name }}-login-jaas-config
stringData:
  login.config: |
    activemq {
  {{- if .Values.authentication.ldapRealm.enabled }}
       org.apache.activemq.artemis.spi.core.security.jaas.LDAPLoginModule sufficient
          debug=true
          reload=true
          initialContextFactory="com.sun.jndi.ldap.LdapCtxFactory"
          connectionURL="{{ .Values.authentication.ldapRealm.url }}"
          connectionUsername="{{ .Values.authentication.ldapRealm.principal }}"
    {{- if and .Values.authentication.ldapRealm.credentialSecret
      .Values.authentication.ldapRealm.credentialAlias }}
          connectionPassword="${ldap.connection.password}"
    {{- end }}
          connectionProtocol="s"
          connectionTimeout="{{ .Values.authentication.ldapRealm.connectionTimeout }}"
          authentication="simple"
          userBase="{{ .Values.authentication.ldapRealm.userBase }}"
          userSearchMatching="(uid={0})"
          userSearchSubtree=true
          readTimeout="{{ .Values.authentication.ldapRealm.connectionTimeout }}"
          roleBase="{{ .Values.authentication.ldapRealm.roleBase }}"
          roleName="cn"
          roleSearchMatching="(member={0})"
          roleSearchSubtree=true
          ;
  {{- end }}  
  {{- if and .Values.authentication.propertiesRealm.enabled .Values.authentication.propertiesRealm.credentialsSecretName }}
       org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=true
          org.apache.activemq.jaas.properties.user="custom-users.properties"
          org.apache.activemq.jaas.properties.role="custom-roles.properties"
          baseDir="/amq/extra/secrets/{{ .Values.authentication.propertiesRealm.credentialsSecretName }}"
          ;
  {{- end }}
       org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
          reload=false
          org.apache.activemq.jaas.properties.user="artemis-users.properties"
          org.apache.activemq.jaas.properties.role="artemis-roles.properties"
          baseDir="/home/jboss/amq-broker/etc"
          ;
    };
type: Opaque
{{- end }}